name: Otterbop
favicon: null
layout_spectrum: 0.14147887704893947
typography_spectrum: 0.7548040531110018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9253275061491877
  lightness: 0.7901107326615602
  saturation: 0.7593329399824142
  rhythmicContrast: 0.8132319091819227
purpose: []
