cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2493734
  brandStrength: 0.8615288
  lightness: 0
  brandColors:
    - '#000000'
    - '#FAE8C7'
    - '#DF6E28'
    - '#322D26'
    - '#881F03'
  rhythmicContrast: 0.2537594
typography_spectrum: 0.4874687
layout_spectrum: 0.7631579
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Otterbop
